### ISSUE TITLE
Ansible playbooks documentation

### ISSUE THREAD

**Issue by YasminBeatriz** [open-power-host-os/infrastructure#92]
The documentation on how to run the Ansible Playbooks lacks some information to a beginner user, e.g. where to find the description of the variables from `vars.yaml`, in case the user is not sure what to set. Other details could be addressed by providing a link to the Ansible documentation.

**Comment by mopsfelder** [comment]
When we have a more specific issue to be addressed, we can reopen and update this or submit a new one.
